In [7]:
import numpy as np
import matplotlib.pyplot as plt
import time
from concurrent.futures import ThreadPoolExecutor
import concurrent.futures
import pandas as pd
import os


def parallel_matrix_multiplication(A, B, num_cpus):

    with ThreadPoolExecutor(max_workers=num_cpus) as executor:
        futures = []
        for i in range(len(A)):
            futures.append(executor.submit(np.matmul, A[i], B))
        results = [f.result() for f in concurrent.futures.as_completed(futures)]
    return np.array(results)
 

def print_test_and_result(A, B, num_cpus ):
    computed_result = parallel_matrix_multiplication(A, B, num_cpus)
    correct_results = np.matmul(A, B)
    if not np.allclose(computed_result, correct_results):
        print(f"Difference in results the correct result is: \n {correct_results} \n\n computed result: with {num_cpus} CPUS \n {computed_result} ")
    else:
        print(f"correct result with {num_cpus}")

A_tests = [
    np.array([[0, 0, 0], [1, 1, 1], [1, 1, 1]]),
    np.array([[1, 1, 1], [2, 2, 2], [0, 0, 0]]),
    np.array([[0, 0, 0], [2, 2, 2], [0, 0, 0]]),
    np.array([[0, 1, 0], [0, 1, 0], [0, -1, 0]])
]

B_test = np.array([[2, 2, 2], [1, 1, 1], [0, 0, 0]])

correct_results = [
    np.array([[0, 0, 0], [3, 3, 3], [3, 3, 3]]),
    np.array([[3, 3, 3], [6, 6, 6], [0, 0, 0]]),
    np.array([[0, 0, 0], [6, 6, 6], [0, 0, 0]]),
    np.array([[1, 1, 1], [1, 1, 1], [-1, -1, -1]])
]
# Number of CPU cores to use
num_cpus = [1, 2, 4, 8]
for i, A in enumerate(A_tests):
    for num_cpu in num_cpus:
        print_test_and_result(A_tests[i], B_test,num_cpu)

correct result with 1
correct result with 2
correct result with 4
Difference in results the correct result is: 
 [[0 0 0]
 [3 3 3]
 [3 3 3]] 

 computed result: with 8 CPUS 
 [[3 3 3]
 [3 3 3]
 [0 0 0]] 
correct result with 1
Difference in results the correct result is: 
 [[3 3 3]
 [6 6 6]
 [0 0 0]] 

 computed result: with 2 CPUS 
 [[3 3 3]
 [0 0 0]
 [6 6 6]] 
Difference in results the correct result is: 
 [[3 3 3]
 [6 6 6]
 [0 0 0]] 

 computed result: with 4 CPUS 
 [[0 0 0]
 [6 6 6]
 [3 3 3]] 
Difference in results the correct result is: 
 [[3 3 3]
 [6 6 6]
 [0 0 0]] 

 computed result: with 8 CPUS 
 [[6 6 6]
 [3 3 3]
 [0 0 0]] 
correct result with 1
Difference in results the correct result is: 
 [[0 0 0]
 [6 6 6]
 [0 0 0]] 

 computed result: with 2 CPUS 
 [[0 0 0]
 [0 0 0]
 [6 6 6]] 
correct result with 4
correct result with 8
correct result with 1
Difference in results the correct result is: 
 [[ 1  1  1]
 [ 1  1  1]
 [-1 -1 -1]] 

 computed result: with 2 CPUS 
 [[ 1  1  1]
 [-1